/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.de.venta.pantallas;

import javax.swing.JButton;
import punto.de.venta.acciones.AccionesBebidas;

/**
 * clase del panel de bebidas
 *
 * @author Jamal Hassini
 */
public class PanelBebidas extends javax.swing.JPanel {

    public PantallaCajaRegistradora panel;
    private AccionesBebidas acciones;

    /**
     * Constructor del PanelBebidas
     *
     * @param panel es el panel donde se mostraran los botones de bebidas
     */
    public PanelBebidas(PantallaCajaRegistradora panel) {

        acciones = new AccionesBebidas(this);
        this.panel = panel;
        setSize(400, 250);
        setLocation(10, 15);
        initComponents();
        
        acciones.botonAgua();
        acciones.botonCervezas();
        acciones.botonCervezasSin();
        acciones.botonCubatas();
        acciones.botonRefrescos();
        acciones.botonZumos();
       
    }
    
    public JButton getBtnAgua() {
        
        return btnAgua;
    }
    
    public JButton getBtnZumos() {
        
        return btnZumos;
    }
    
    public JButton getBtnRefrescos() {
        
        return btnRefrescos;
    }
    
    public JButton getBtnCervezasSin() {
        
        return btnCervezasSin;
    }
    
    public JButton getBtnCervezas() {
        
        return btnCervezas;
    }
    
    public JButton getBtnCubatas() {
        
        return btnCubatas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCubatas = new javax.swing.JButton();
        btnAgua = new javax.swing.JButton();
        btnZumos = new javax.swing.JButton();
        btnRefrescos = new javax.swing.JButton();
        btnCervezasSin = new javax.swing.JButton();
        btnCervezas = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(280, 195));
        setLayout(null);

        btnCubatas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCubatas.setToolTipText("");
        btnCubatas.setBorder(null);
        btnCubatas.setBorderPainted(false);
        btnCubatas.setContentAreaFilled(false);
        btnCubatas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCubatas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCubatas.setIconTextGap(5);
        btnCubatas.setPreferredSize(new java.awt.Dimension(90, 102));
        btnCubatas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCubatas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCubatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubatasActionPerformed(evt);
            }
        });
        add(btnCubatas);
        btnCubatas.setBounds(290, 140, 110, 110);

        btnAgua.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAgua.setToolTipText("");
        btnAgua.setBorder(null);
        btnAgua.setBorderPainted(false);
        btnAgua.setContentAreaFilled(false);
        btnAgua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgua.setIconTextGap(5);
        btnAgua.setPreferredSize(new java.awt.Dimension(90, 102));
        btnAgua.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAgua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAguaActionPerformed(evt);
            }
        });
        add(btnAgua);
        btnAgua.setBounds(10, 10, 110, 110);

        btnZumos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnZumos.setToolTipText("");
        btnZumos.setBorder(null);
        btnZumos.setBorderPainted(false);
        btnZumos.setContentAreaFilled(false);
        btnZumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZumos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnZumos.setIconTextGap(5);
        btnZumos.setPreferredSize(new java.awt.Dimension(90, 102));
        btnZumos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnZumos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnZumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZumosActionPerformed(evt);
            }
        });
        add(btnZumos);
        btnZumos.setBounds(150, 10, 110, 110);

        btnRefrescos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnRefrescos.setToolTipText("");
        btnRefrescos.setBorder(null);
        btnRefrescos.setBorderPainted(false);
        btnRefrescos.setContentAreaFilled(false);
        btnRefrescos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefrescos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRefrescos.setIconTextGap(5);
        btnRefrescos.setPreferredSize(new java.awt.Dimension(90, 102));
        btnRefrescos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRefrescos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRefrescos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescosActionPerformed(evt);
            }
        });
        add(btnRefrescos);
        btnRefrescos.setBounds(290, 10, 110, 110);

        btnCervezasSin.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCervezasSin.setToolTipText("");
        btnCervezasSin.setBorder(null);
        btnCervezasSin.setBorderPainted(false);
        btnCervezasSin.setContentAreaFilled(false);
        btnCervezasSin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCervezasSin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCervezasSin.setIconTextGap(5);
        btnCervezasSin.setPreferredSize(new java.awt.Dimension(90, 102));
        btnCervezasSin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCervezasSin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCervezasSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCervezasSinActionPerformed(evt);
            }
        });
        add(btnCervezasSin);
        btnCervezasSin.setBounds(10, 140, 110, 110);

        btnCervezas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCervezas.setToolTipText("");
        btnCervezas.setBorder(null);
        btnCervezas.setBorderPainted(false);
        btnCervezas.setContentAreaFilled(false);
        btnCervezas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCervezas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCervezas.setIconTextGap(5);
        btnCervezas.setPreferredSize(new java.awt.Dimension(90, 102));
        btnCervezas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCervezas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCervezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCervezasActionPerformed(evt);
            }
        });
        add(btnCervezas);
        btnCervezas.setBounds(150, 140, 110, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCubatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubatasActionPerformed
        // Metodo de la clase AccionesBebidas que muestra el agua en la tabla pedidos
       acciones.devolverCubatas();
    }//GEN-LAST:event_btnCubatasActionPerformed

    private void btnAguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAguaActionPerformed
        // TODO add your handling code here:
         acciones.devolverAgua();
    }//GEN-LAST:event_btnAguaActionPerformed

    private void btnZumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZumosActionPerformed
        // TODO add your handling code here:
        acciones.devolverZumos();
    }//GEN-LAST:event_btnZumosActionPerformed

    private void btnRefrescosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescosActionPerformed
        // TODO add your handling code here:
        acciones.devolverRefrescos();
    }//GEN-LAST:event_btnRefrescosActionPerformed

    private void btnCervezasSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCervezasSinActionPerformed
        // TODO add your handling code here:
        acciones.devolverCervezasSin();
    }//GEN-LAST:event_btnCervezasSinActionPerformed

    private void btnCervezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCervezasActionPerformed
        // TODO add your handling code here:
        acciones.devolverCervezas();
    }//GEN-LAST:event_btnCervezasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgua;
    private javax.swing.JButton btnCervezas;
    private javax.swing.JButton btnCervezasSin;
    private javax.swing.JButton btnCubatas;
    private javax.swing.JButton btnRefrescos;
    private javax.swing.JButton btnZumos;
    // End of variables declaration//GEN-END:variables

}
