/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.de.venta.pantallas;

import javax.swing.JButton;
import punto.de.venta.acciones.AccionesComplimentos;

/**
 * Clase del panelComplimentos
 *
 * @author Jamal Hassini
 */
public class PanelComplimentos extends javax.swing.JPanel {

    public PantallaCajaRegistradora panel;
    private AccionesComplimentos acciones;

    /**
     * Constructor del panelComplimentos
     *
     * @param panel es el panel donde se mostraran los botones de complimentos
     */
    public PanelComplimentos(PantallaCajaRegistradora panel) {
        acciones = new AccionesComplimentos(this);
        this.panel = panel;
        setSize(400, 250);
        setLocation(10, 15);
        initComponents();
        
        acciones.botonPatatasAsadas();
        acciones.botonPatatasFritas();
        acciones.botonArosDeCebolla();
    }
    
    
    public JButton getBtnPatatasAsadas() {
        
        return btnPatatasAsadas;
    }
    
    public JButton getBtnPatatasFritas() {
        
        return btnPatatasFritas;
    }
    
    public JButton getBtnArosDeCebolla() {
        
        return btnArosDeCebolla;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPatatasFritas = new javax.swing.JButton();
        btnPatatasAsadas = new javax.swing.JButton();
        btnArosDeCebolla = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(null);

        btnPatatasFritas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPatatasFritas.setToolTipText("");
        btnPatatasFritas.setBorder(null);
        btnPatatasFritas.setBorderPainted(false);
        btnPatatasFritas.setContentAreaFilled(false);
        btnPatatasFritas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPatatasFritas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPatatasFritas.setIconTextGap(3);
        btnPatatasFritas.setPreferredSize(new java.awt.Dimension(90, 102));
        btnPatatasFritas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPatatasFritas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPatatasFritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatatasFritasActionPerformed(evt);
            }
        });
        add(btnPatatasFritas);
        btnPatatasFritas.setBounds(10, 20, 110, 120);

        btnPatatasAsadas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnPatatasAsadas.setToolTipText("");
        btnPatatasAsadas.setBorder(null);
        btnPatatasAsadas.setBorderPainted(false);
        btnPatatasAsadas.setContentAreaFilled(false);
        btnPatatasAsadas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPatatasAsadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPatatasAsadas.setIconTextGap(3);
        btnPatatasAsadas.setPreferredSize(new java.awt.Dimension(90, 102));
        btnPatatasAsadas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPatatasAsadas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPatatasAsadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatatasAsadasActionPerformed(evt);
            }
        });
        add(btnPatatasAsadas);
        btnPatatasAsadas.setBounds(130, 20, 110, 120);

        btnArosDeCebolla.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnArosDeCebolla.setToolTipText("");
        btnArosDeCebolla.setBorder(null);
        btnArosDeCebolla.setBorderPainted(false);
        btnArosDeCebolla.setContentAreaFilled(false);
        btnArosDeCebolla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArosDeCebolla.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArosDeCebolla.setIconTextGap(3);
        btnArosDeCebolla.setPreferredSize(new java.awt.Dimension(90, 102));
        btnArosDeCebolla.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnArosDeCebolla.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnArosDeCebolla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArosDeCebollaActionPerformed(evt);
            }
        });
        add(btnArosDeCebolla);
        btnArosDeCebolla.setBounds(250, 20, 110, 120);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatatasFritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatatasFritasActionPerformed
        // Metodo de la clase AccionesBebidas que muestra patatas fritas en la tabla pedidos
        acciones.devolverFritas();
    }//GEN-LAST:event_btnPatatasFritasActionPerformed

    private void btnPatatasAsadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatatasAsadasActionPerformed
        // Metodo de la clase AccionesBebidas que muestra patatas asadas en la tabla pedidos
        acciones.devolverAsadas();
        //acciones.devolverAsadas();
    }//GEN-LAST:event_btnPatatasAsadasActionPerformed

    private void btnArosDeCebollaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArosDeCebollaActionPerformed
        // Metodo de la clase AccionesBebidas que muestra aros de cebolla en la tabla pedidos
        //acciones.devolverAros();
        acciones.devolverAros();
    }//GEN-LAST:event_btnArosDeCebollaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnArosDeCebolla;
    public javax.swing.JButton btnPatatasAsadas;
    public javax.swing.JButton btnPatatasFritas;
    // End of variables declaration//GEN-END:variables
}
