/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.de.venta.pantallas;

import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import punto.de.venta.acciones.AccionesAjustesProductos;

/**
 *
 * @author Usuario1
 */
public class PanelModificaProducto extends javax.swing.JFrame {

    private PanelAjustesProductos panel4;
    private AccionesAjustesProductos acciones;

    /**
     * Creates new form PanelModificaProducto
     */
    public PanelModificaProducto() {

        acciones = new AccionesAjustesProductos(this);
        this.setTitle("Modificacion de Producto");
        initComponents();
        acciones.modificarPoducto();
    }

    public JTextField getTxtDescripcion() {
        return txtDescripcion;
    }

    public JTextField getTxtId() {

        return txtId;
    }

    public JComboBox getCmbCategorias() {
        return cmbCategorias;
    }

    public JTextField getTxtPrecio() {
        return txtPrecio;
    }

    public JTextField getTxtCantidad() {
        return txtCantidad;
    }

    

    public JLabel getLblNuevaImagenP() {

        return lblNuevaImagenP;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        cmbCategorias = new javax.swing.JComboBox<>();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblNuevaImagenP = new javax.swing.JLabel();
        btnBuscarP = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbldescripcion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbldescripcion.setText("Descripcion");
        jPanel1.add(lbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 257, 23));

        txtDescripcion.setEditable(false);
        txtDescripcion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 270, 32));

        lblPrecio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblPrecio.setText("Precio");
        jPanel1.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 59, 23));

        txtPrecio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 86, -1));

        cmbCategorias.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        cmbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria" }));
        jPanel1.add(cmbCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 220, 36));

        lblCantidad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCantidad.setText("Cantidad ");
        jPanel1.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 82, -1));

        btnGuardar.setBackground(new java.awt.Color(102, 0, 102));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 145, 42));

        lblNuevaImagenP.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblNuevaImagenP.setForeground(new java.awt.Color(204, 204, 204));
        lblNuevaImagenP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNuevaImagenP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lblNuevaImagenP, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 190, 170));

        btnBuscarP.setBackground(new java.awt.Color(102, 0, 102));
        btnBuscarP.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnBuscarP.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarP.setText("BUSCAR IMAGEN");
        btnBuscarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarPMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 226, 42));

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 190, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Id del producto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        txtId.setEditable(false);
        txtId.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 60, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        acciones.actualizaProducto();
        dispose();
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnBuscarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarPMouseClicked
        // TODO add your handling code here:
       acciones.modificaImagenProducto();

    }//GEN-LAST:event_btnBuscarPMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarP;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbCategorias;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblNuevaImagenP;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
