/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.de.venta.pantallas;

import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import punto.de.venta.acciones.AccionesConfigBotones;
import static punto.de.venta.gestionbd.ServiceBebidas.SQLBotonCervezasSin;
import punto.de.venta.principal.PuntoDeVentaFrame;

/**
 *
 * @author Usuario1
 */
public class PanelConfigBotones extends javax.swing.JPanel {

    
    
    
/**
     * Creates new form PanelConfigBotones
     */
        private PuntoDeVentaFrame frame;
    private AccionesConfigBotones acciones;
    
    /**
     * Creates new form PanelListarStock
     * @param frame
     */
    public PanelConfigBotones(PuntoDeVentaFrame frame) {
        //acciones= new AccionesConfigBotones();
        
        acciones = new AccionesConfigBotones(this);
        this.frame = frame;
        frame.setTitle("Ajustes categorias");
        initComponents();
        acciones.muestraSentencias();
    }
    
    public JTextField getTxtSentencia(){
        
        return txtSentencia;
    }
    
    public JTextField getTxtSentencia1(){
        
        return txtSentencia1;
    }
    
    public JTextField getTxtSentencia2(){
        
        return txtSentencia2;
    }
    
    public JTextField getTxtSentencia3(){
        
        return txtSentencia3;
    }
    
    public JTextField getTxtSentencia4(){
        
        return txtSentencia4;
    }
    public JTextField getTxtSentencia5(){
        
        return txtSentencia5;
    }
    
    public JTextField getTxtSentencia6(){
        
        return txtSentencia6;
    }
    
    public JTextField getTxtSentencia7(){
        
        return txtSentencia7;
    }
    
    public JTextField getTxtSentencia8(){
        
        return txtSentencia8;
    }
    
    public JTextField getTxtSentencia9(){
        
        return txtSentencia9;
    }
    public JTextField getTxtSentencia10(){
        
        return txtSentencia10;
    }
    
    public JTextField getTxtSentencia11(){
        
        return txtSentencia11;
    }
    
    public JTextField getTxtSentencia12(){
        
        return txtSentencia12;
    }
    
    public JTextField getTxtSentencia13(){
        
        return txtSentencia13;
    }
    
    public JTextField getTxtSentencia14(){
        
        return txtSentencia14;
    }
    
    public JTextField getTxtSentencia15(){
        
        return txtSentencia15;
    }
    public JTextField getTxtSentencia16(){
        
        return txtSentencia16;
    }
    
    public JTextField getTxtSentencia17(){
        
        return txtSentencia17;
    }
    
    public JTextField getTxtSentencia18(){
        
        return txtSentencia18;
    }
    
    public JTextField getTxtSentencia19(){
        
        return txtSentencia19;
    }
    
    public JTextField getTxtSentencia20(){
        
        return txtSentencia20;
    }
    public JTextField getTxtSentencia21(){
        
        return txtSentencia21;
    }
    
    public JTextField getTxtSentencia22(){
        
        return txtSentencia22;
    }
    
    public JTextField getTxtSentencia23(){
        
        return txtSentencia23;
    }
    
    public JTextField getTxtSentencia24(){
        
        return txtSentencia24;
    }
    
    public JTextField getTxtSentencia25(){
        
        return txtSentencia25;
    }
    public JTextField getTxtSentencia26(){
        
        return txtSentencia26;
    }
    
    public JTextField getTxtSentencia27(){
        
        return txtSentencia27;
    }
    
    public JTextField getTxtSentencia28(){
        
        return txtSentencia28;
    }
    
    public JTextField getTxtSentencia29(){
        
        return txtSentencia29;
    }
    
    public JTextField getTxtSentencia30(){
        
        return txtSentencia30;
    }
    
    public JTextField getTxtSentencia31(){
        
        return txtSentencia31;
    }
    
    public JTextField getTxtSentencia32(){
        
        return txtSentencia32;
    }
    
    public JTextField getTxtSentencia33(){
        
        return txtSentencia33;
    }
    
    public JTextField getTxtSentencia34(){
        
        return txtSentencia34;
    }
    
    public JTextField getTxtSentencia35(){
        
        return txtSentencia35;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtSentencia = new javax.swing.JTextField();
        txtSentencia1 = new javax.swing.JTextField();
        txtSentencia2 = new javax.swing.JTextField();
        txtSentencia3 = new javax.swing.JTextField();
        txtSentencia4 = new javax.swing.JTextField();
        txtSentencia5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtSentencia6 = new javax.swing.JTextField();
        txtSentencia7 = new javax.swing.JTextField();
        txtSentencia8 = new javax.swing.JTextField();
        txtSentencia9 = new javax.swing.JTextField();
        txtSentencia10 = new javax.swing.JTextField();
        txtSentencia11 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        txtSentencia12 = new javax.swing.JTextField();
        txtSentencia13 = new javax.swing.JTextField();
        txtSentencia14 = new javax.swing.JTextField();
        txtSentencia15 = new javax.swing.JTextField();
        txtSentencia16 = new javax.swing.JTextField();
        txtSentencia17 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtSentencia18 = new javax.swing.JTextField();
        txtSentencia19 = new javax.swing.JTextField();
        txtSentencia20 = new javax.swing.JTextField();
        txtSentencia21 = new javax.swing.JTextField();
        txtSentencia22 = new javax.swing.JTextField();
        txtSentencia23 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtSentencia24 = new javax.swing.JTextField();
        txtSentencia25 = new javax.swing.JTextField();
        txtSentencia26 = new javax.swing.JTextField();
        txtSentencia27 = new javax.swing.JTextField();
        txtSentencia28 = new javax.swing.JTextField();
        txtSentencia29 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtSentencia30 = new javax.swing.JTextField();
        txtSentencia31 = new javax.swing.JTextField();
        txtSentencia32 = new javax.swing.JTextField();
        txtSentencia33 = new javax.swing.JTextField();
        txtSentencia34 = new javax.swing.JTextField();
        txtSentencia35 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuracion de botones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Complimentos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtSentencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 468, -1));
        jPanel2.add(txtSentencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, 468, -1));
        jPanel2.add(txtSentencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, 468, -1));

        txtSentencia3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentencia3ActionPerformed(evt);
            }
        });
        jPanel2.add(txtSentencia3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 468, -1));
        jPanel2.add(txtSentencia4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, 468, -1));
        jPanel2.add(txtSentencia5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, 468, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 480, 180));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bebidas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        txtSentencia9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentencia9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSentencia6, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSentencia7, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSentencia8, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSentencia9, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSentencia10, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSentencia11, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtSentencia6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtSentencia7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtSentencia8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtSentencia9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtSentencia10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(txtSentencia11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 470, 180));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrantes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(txtSentencia12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 453, -1));
        jPanel4.add(txtSentencia13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, 453, -1));
        jPanel4.add(txtSentencia14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, 453, -1));

        txtSentencia15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentencia15ActionPerformed(evt);
            }
        });
        jPanel4.add(txtSentencia15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 453, -1));
        jPanel4.add(txtSentencia16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, 453, -1));
        jPanel4.add(txtSentencia17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, 453, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 475, 180));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Postres", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(txtSentencia18, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 19, 453, -1));
        jPanel5.add(txtSentencia19, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 45, 453, -1));
        jPanel5.add(txtSentencia20, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 71, 453, -1));

        txtSentencia21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentencia21ActionPerformed(evt);
            }
        });
        jPanel5.add(txtSentencia21, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 97, 453, -1));
        jPanel5.add(txtSentencia22, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 123, 453, -1));
        jPanel5.add(txtSentencia23, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 149, 453, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 480, 180));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hamburguesas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(txtSentencia24, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 453, -1));
        jPanel6.add(txtSentencia25, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, 453, -1));
        jPanel6.add(txtSentencia26, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, 453, -1));

        txtSentencia27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentencia27ActionPerformed(evt);
            }
        });
        jPanel6.add(txtSentencia27, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 453, -1));
        jPanel6.add(txtSentencia28, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 123, 453, -1));
        jPanel6.add(txtSentencia29, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 149, 453, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 475, 180));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cafes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(txtSentencia30, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 19, 453, -1));
        jPanel7.add(txtSentencia31, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 45, 453, -1));
        jPanel7.add(txtSentencia32, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 71, 453, -1));

        txtSentencia33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentencia33ActionPerformed(evt);
            }
        });
        jPanel7.add(txtSentencia33, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 97, 453, -1));
        jPanel7.add(txtSentencia34, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 123, 453, -1));
        jPanel7.add(txtSentencia35, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 149, 453, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 480, 180));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar cambios");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 330, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSentencia3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentencia3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSentencia3ActionPerformed

    private void txtSentencia9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentencia9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSentencia9ActionPerformed

    private void txtSentencia15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentencia15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSentencia15ActionPerformed

    private void txtSentencia21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentencia21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSentencia21ActionPerformed

    private void txtSentencia27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentencia27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSentencia27ActionPerformed

    private void txtSentencia33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentencia33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSentencia33ActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        acciones.guardaCambios();
    }//GEN-LAST:event_btnGuardarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtSentencia;
    private javax.swing.JTextField txtSentencia1;
    private javax.swing.JTextField txtSentencia10;
    private javax.swing.JTextField txtSentencia11;
    private javax.swing.JTextField txtSentencia12;
    private javax.swing.JTextField txtSentencia13;
    private javax.swing.JTextField txtSentencia14;
    private javax.swing.JTextField txtSentencia15;
    private javax.swing.JTextField txtSentencia16;
    private javax.swing.JTextField txtSentencia17;
    private javax.swing.JTextField txtSentencia18;
    private javax.swing.JTextField txtSentencia19;
    private javax.swing.JTextField txtSentencia2;
    private javax.swing.JTextField txtSentencia20;
    private javax.swing.JTextField txtSentencia21;
    private javax.swing.JTextField txtSentencia22;
    private javax.swing.JTextField txtSentencia23;
    private javax.swing.JTextField txtSentencia24;
    private javax.swing.JTextField txtSentencia25;
    private javax.swing.JTextField txtSentencia26;
    private javax.swing.JTextField txtSentencia27;
    private javax.swing.JTextField txtSentencia28;
    private javax.swing.JTextField txtSentencia29;
    private javax.swing.JTextField txtSentencia3;
    private javax.swing.JTextField txtSentencia30;
    private javax.swing.JTextField txtSentencia31;
    private javax.swing.JTextField txtSentencia32;
    private javax.swing.JTextField txtSentencia33;
    private javax.swing.JTextField txtSentencia34;
    private javax.swing.JTextField txtSentencia35;
    private javax.swing.JTextField txtSentencia4;
    private javax.swing.JTextField txtSentencia5;
    private javax.swing.JTextField txtSentencia6;
    private javax.swing.JTextField txtSentencia7;
    private javax.swing.JTextField txtSentencia8;
    private javax.swing.JTextField txtSentencia9;
    // End of variables declaration//GEN-END:variables

   
}
