/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.de.venta.pantallas;

import javax.swing.JButton;
import punto.de.venta.acciones.AccionesEntrantes;

/**
 * Clase con el panel de entrantes
 *
 * @author Jamal Hassini
 */
public class PanelEntrantes extends javax.swing.JPanel {

    public PantallaCajaRegistradora panel;
    private AccionesEntrantes acciones;

    /**
     * Constructor del panelEntrantes
     *
     * @param panel es el panel donde se mostraran los botones de entrantes
     */
    public PanelEntrantes(PantallaCajaRegistradora panel) {

        acciones = new AccionesEntrantes(this);
        this.panel = panel;
        setSize(400, 250);
        setLocation(10, 15);
        initComponents();
        
        acciones.botonEnsaladaMediterranea();
        acciones.botonEnsaladaCesar();
        acciones.botonEnsaladillaRusa();
        acciones.botonMontaditos();
        acciones.botonNachos();
    }
    
    public JButton getBtnEnsaladaCesar() {
        
        return btnEnsaladaCesar;
    }
    public JButton getBtnEnsaladaMediterranea() {
        
        return btnEnsaladaMediterranea;
    }
    
    public JButton getBtnEnsaladillaRusa() {
        
        return btnEnsaladillaRusa;
    }
    
    public JButton getBtnMontaditos() {
        
        return btnMontaditos;
    }
    
    public JButton getBtnNachos() {
        
        return btnNachos;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnsaladaMediterranea = new javax.swing.JButton();
        btnNachos = new javax.swing.JButton();
        btnEnsaladillaRusa = new javax.swing.JButton();
        btnMontaditos = new javax.swing.JButton();
        btnEnsaladaCesar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(280, 195));
        setRequestFocusEnabled(false);
        setLayout(null);

        btnEnsaladaMediterranea.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEnsaladaMediterranea.setToolTipText("");
        btnEnsaladaMediterranea.setBorder(null);
        btnEnsaladaMediterranea.setBorderPainted(false);
        btnEnsaladaMediterranea.setContentAreaFilled(false);
        btnEnsaladaMediterranea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnsaladaMediterranea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnsaladaMediterranea.setIconTextGap(3);
        btnEnsaladaMediterranea.setPreferredSize(new java.awt.Dimension(90, 102));
        btnEnsaladaMediterranea.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEnsaladaMediterranea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnsaladaMediterranea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnsaladaMediterraneaActionPerformed(evt);
            }
        });
        add(btnEnsaladaMediterranea);
        btnEnsaladaMediterranea.setBounds(20, 10, 110, 110);

        btnNachos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNachos.setToolTipText("");
        btnNachos.setBorder(null);
        btnNachos.setBorderPainted(false);
        btnNachos.setContentAreaFilled(false);
        btnNachos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNachos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNachos.setIconTextGap(3);
        btnNachos.setPreferredSize(new java.awt.Dimension(90, 102));
        btnNachos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNachos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNachos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNachosActionPerformed(evt);
            }
        });
        add(btnNachos);
        btnNachos.setBounds(280, 10, 110, 110);

        btnEnsaladillaRusa.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEnsaladillaRusa.setToolTipText("");
        btnEnsaladillaRusa.setBorder(null);
        btnEnsaladillaRusa.setBorderPainted(false);
        btnEnsaladillaRusa.setContentAreaFilled(false);
        btnEnsaladillaRusa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnsaladillaRusa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnsaladillaRusa.setIconTextGap(3);
        btnEnsaladillaRusa.setPreferredSize(new java.awt.Dimension(90, 102));
        btnEnsaladillaRusa.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEnsaladillaRusa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnsaladillaRusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnsaladillaRusaActionPerformed(evt);
            }
        });
        add(btnEnsaladillaRusa);
        btnEnsaladillaRusa.setBounds(150, 130, 110, 120);

        btnMontaditos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnMontaditos.setToolTipText("");
        btnMontaditos.setBorder(null);
        btnMontaditos.setBorderPainted(false);
        btnMontaditos.setContentAreaFilled(false);
        btnMontaditos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMontaditos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMontaditos.setIconTextGap(3);
        btnMontaditos.setPreferredSize(new java.awt.Dimension(90, 102));
        btnMontaditos.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMontaditos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMontaditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMontaditosActionPerformed(evt);
            }
        });
        add(btnMontaditos);
        btnMontaditos.setBounds(20, 130, 110, 120);

        btnEnsaladaCesar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEnsaladaCesar.setToolTipText("");
        btnEnsaladaCesar.setBorder(null);
        btnEnsaladaCesar.setBorderPainted(false);
        btnEnsaladaCesar.setContentAreaFilled(false);
        btnEnsaladaCesar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnsaladaCesar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnsaladaCesar.setIconTextGap(3);
        btnEnsaladaCesar.setPreferredSize(new java.awt.Dimension(90, 102));
        btnEnsaladaCesar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEnsaladaCesar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnsaladaCesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnsaladaCesarActionPerformed(evt);
            }
        });
        add(btnEnsaladaCesar);
        btnEnsaladaCesar.setBounds(150, 10, 110, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnsaladaMediterraneaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnsaladaMediterraneaActionPerformed
        // Metodo de la clase AccionesEntrantes que muestra Ensalada en la tabla pedidos
        acciones.devolverEnsalada();
    }//GEN-LAST:event_btnEnsaladaMediterraneaActionPerformed

    private void btnEnsaladaCesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnsaladaCesarActionPerformed
        // Metodo de la clase AccionesEntrantes que muestra Ensalada cesar en la tabla pedidos
        acciones.devolverCesar();
    }//GEN-LAST:event_btnEnsaladaCesarActionPerformed

    private void btnNachosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNachosActionPerformed
        // Metodo de la clase AccionesEntrantes que muestra los nachos en la tabla pedidos
        acciones.devolverNachos();
    }//GEN-LAST:event_btnNachosActionPerformed

    private void btnMontaditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMontaditosActionPerformed
        // Metodo de la clase AccionesEntrantes que muestra los montaditos en la tabla pedidos
        acciones.devolverMontadito();
    }//GEN-LAST:event_btnMontaditosActionPerformed

    private void btnEnsaladillaRusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnsaladillaRusaActionPerformed
        // Metodo de la clase AccionesEntrantes que muestra Ensaladilla rusa en la tabla pedidos
        acciones.devolverEnsaladilla();
    }//GEN-LAST:event_btnEnsaladillaRusaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnsaladaCesar;
    private javax.swing.JButton btnEnsaladaMediterranea;
    private javax.swing.JButton btnEnsaladillaRusa;
    private javax.swing.JButton btnMontaditos;
    private javax.swing.JButton btnNachos;
    // End of variables declaration//GEN-END:variables
}
