/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.de.venta.pantallas;

import javax.swing.JButton;
import punto.de.venta.acciones.AccionesHamburguesas;

/**
 * Clase con el panel de hamburguesas
 *
 * @author Jamal Hassini
 */
public class PanelHamburguesas extends javax.swing.JPanel {

    public PantallaCajaRegistradora panel;
    private AccionesHamburguesas acciones;

    /**
     * constructor del PanelHamburguesas
     *
     * @param panel es el panel donde se mostraran los botones de hamburguesas
     */
    public PanelHamburguesas(PantallaCajaRegistradora panel) {

        acciones = new AccionesHamburguesas(this);
        this.panel = panel;
        setSize(400, 250);
        setLocation(3, 13);
        initComponents();
        
        acciones.botonHamburguesaDoble();
        acciones.botonHamburguesaDoblePollo();
        acciones.botonHamburguesaNormal();
        acciones.botonHamburguesaTernera();
        acciones.botonHamburguesaTernera200g();
        acciones.botonHamburguesaPollo();
    }
    
    public JButton getBtnHamburguesaNormal() {
        
        return btnHamburguesaNormal;
    }
    
    public JButton getBtnHamburguesaDoble() {
        
        return btnHamburguesaDoble;
    }
    
    public JButton getBtnHamburguesaPollo() {
        
        return btnHamburguesaPollo;
    }
    
    public JButton getBtnHamburguesaDoblePollo() {
        
        return btnHamburguesaDoblePollo;
    }
    
    public JButton getBtnHamburguesaTernera() {
        
        return btnHamburguesaTernera;
    }
    
    public JButton getBtnHamburguesaTernera200g() {
        
        return btnHamburguesaTernera200g;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHamburguesaNormal = new javax.swing.JButton();
        btnHamburguesaDoble = new javax.swing.JButton();
        btnHamburguesaPollo = new javax.swing.JButton();
        btnHamburguesaDoblePollo = new javax.swing.JButton();
        btnHamburguesaTernera = new javax.swing.JButton();
        btnHamburguesaTernera200g = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(280, 195));
        setLayout(null);

        btnHamburguesaNormal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHamburguesaNormal.setToolTipText("");
        btnHamburguesaNormal.setBorder(null);
        btnHamburguesaNormal.setBorderPainted(false);
        btnHamburguesaNormal.setContentAreaFilled(false);
        btnHamburguesaNormal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHamburguesaNormal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHamburguesaNormal.setIconTextGap(3);
        btnHamburguesaNormal.setPreferredSize(new java.awt.Dimension(90, 102));
        btnHamburguesaNormal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaNormal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesaNormalActionPerformed(evt);
            }
        });
        add(btnHamburguesaNormal);
        btnHamburguesaNormal.setBounds(20, 10, 100, 110);

        btnHamburguesaDoble.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHamburguesaDoble.setToolTipText("");
        btnHamburguesaDoble.setBorder(null);
        btnHamburguesaDoble.setBorderPainted(false);
        btnHamburguesaDoble.setContentAreaFilled(false);
        btnHamburguesaDoble.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHamburguesaDoble.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHamburguesaDoble.setIconTextGap(3);
        btnHamburguesaDoble.setPreferredSize(new java.awt.Dimension(90, 102));
        btnHamburguesaDoble.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaDoble.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesaDobleActionPerformed(evt);
            }
        });
        add(btnHamburguesaDoble);
        btnHamburguesaDoble.setBounds(150, 10, 110, 110);

        btnHamburguesaPollo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHamburguesaPollo.setToolTipText("");
        btnHamburguesaPollo.setBorder(null);
        btnHamburguesaPollo.setBorderPainted(false);
        btnHamburguesaPollo.setContentAreaFilled(false);
        btnHamburguesaPollo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHamburguesaPollo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHamburguesaPollo.setIconTextGap(3);
        btnHamburguesaPollo.setPreferredSize(new java.awt.Dimension(90, 102));
        btnHamburguesaPollo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaPollo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesaPolloActionPerformed(evt);
            }
        });
        add(btnHamburguesaPollo);
        btnHamburguesaPollo.setBounds(290, 10, 120, 110);

        btnHamburguesaDoblePollo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHamburguesaDoblePollo.setToolTipText("");
        btnHamburguesaDoblePollo.setBorder(null);
        btnHamburguesaDoblePollo.setBorderPainted(false);
        btnHamburguesaDoblePollo.setContentAreaFilled(false);
        btnHamburguesaDoblePollo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHamburguesaDoblePollo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHamburguesaDoblePollo.setIconTextGap(3);
        btnHamburguesaDoblePollo.setPreferredSize(new java.awt.Dimension(90, 102));
        btnHamburguesaDoblePollo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaDoblePollo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaDoblePollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesaDoblePolloActionPerformed(evt);
            }
        });
        add(btnHamburguesaDoblePollo);
        btnHamburguesaDoblePollo.setBounds(20, 140, 100, 110);

        btnHamburguesaTernera.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHamburguesaTernera.setToolTipText("");
        btnHamburguesaTernera.setBorder(null);
        btnHamburguesaTernera.setBorderPainted(false);
        btnHamburguesaTernera.setContentAreaFilled(false);
        btnHamburguesaTernera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHamburguesaTernera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHamburguesaTernera.setIconTextGap(3);
        btnHamburguesaTernera.setPreferredSize(new java.awt.Dimension(90, 102));
        btnHamburguesaTernera.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaTernera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaTernera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesaTerneraActionPerformed(evt);
            }
        });
        add(btnHamburguesaTernera);
        btnHamburguesaTernera.setBounds(150, 140, 110, 110);

        btnHamburguesaTernera200g.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHamburguesaTernera200g.setToolTipText("");
        btnHamburguesaTernera200g.setBorder(null);
        btnHamburguesaTernera200g.setBorderPainted(false);
        btnHamburguesaTernera200g.setContentAreaFilled(false);
        btnHamburguesaTernera200g.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHamburguesaTernera200g.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHamburguesaTernera200g.setIconTextGap(3);
        btnHamburguesaTernera200g.setPreferredSize(new java.awt.Dimension(90, 102));
        btnHamburguesaTernera200g.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaTernera200g.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHamburguesaTernera200g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHamburguesaTernera200gActionPerformed(evt);
            }
        });
        add(btnHamburguesaTernera200g);
        btnHamburguesaTernera200g.setBounds(290, 140, 120, 110);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHamburguesaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaNormalActionPerformed
        // Metodo de la clase AccionesHamburguesas que muestra hamburguesa normal en la tabla pedidos
        acciones.devolverNormal();
    }//GEN-LAST:event_btnHamburguesaNormalActionPerformed

    private void btnHamburguesaDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaDobleActionPerformed
        // Metodo de la clase AccionesHamburguesas que muestra hamburguesa doble en la tabla pedidos
        acciones.devolverDoble();
    }//GEN-LAST:event_btnHamburguesaDobleActionPerformed

    private void btnHamburguesaPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaPolloActionPerformed
        // Metodo de la clase AccionesHamburguesas que muestra hamburguesa de pollo en la tabla pedidos
        acciones.devolverPollo();
    }//GEN-LAST:event_btnHamburguesaPolloActionPerformed

    private void btnHamburguesaDoblePolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaDoblePolloActionPerformed
        // Metodo de la clase AccionesHamburguesas que muestra hamburguesa de pollo doble en la tabla pedidos
        acciones.devolverDoblePollo();
    }//GEN-LAST:event_btnHamburguesaDoblePolloActionPerformed

    private void btnHamburguesaTerneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaTerneraActionPerformed
        // Metodo de la clase AccionesHamburguesas que muestra hamburguesa de ternera en la tabla pedidos
        acciones.devolverTernera();
    }//GEN-LAST:event_btnHamburguesaTerneraActionPerformed

    private void btnHamburguesaTernera200gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHamburguesaTernera200gActionPerformed
        // Metodo de la clase AccionesHamburguesas que muestra hamburguesa de ternera200g en la tabla pedidos
        acciones.devolverTernera200();
    }//GEN-LAST:event_btnHamburguesaTernera200gActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHamburguesaDoble;
    private javax.swing.JButton btnHamburguesaDoblePollo;
    private javax.swing.JButton btnHamburguesaNormal;
    private javax.swing.JButton btnHamburguesaPollo;
    private javax.swing.JButton btnHamburguesaTernera;
    private javax.swing.JButton btnHamburguesaTernera200g;
    // End of variables declaration//GEN-END:variables
}
