/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.de.venta.pantallas;

import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import punto.de.venta.acciones.AccionesPedidosCliente;
import punto.de.venta.principal.PuntoDeVentaFrame;

/**
 * Clase con la PantallaPedidosCliente
 *
 * @author Jamal Hassini
 */
public class PantallaPedidosCliente extends javax.swing.JPanel {

    private PuntoDeVentaFrame frame;
    private AccionesPedidosCliente acciones;

    /**
     * Constructor de la pantallaPedidosCliente
     *
     * @param frame PuntoDeVentaFrame ventana en la que se mostrará la pantalla
     */
    public PantallaPedidosCliente(PuntoDeVentaFrame frame) {

        acciones = new AccionesPedidosCliente(this);
        this.frame = frame;
        frame.setTitle("Pedidos por cliente");
        initComponents();

        acciones.ajustarCeldas();// Metodo de la clase accionesClientes que ajusta las celdas de la tblPedidosClientes
        acciones.devuelveClientes();// Metodo de la clase accionesClientes que carga los clientes en el JCombobos cmbClientes1        
    }

    /**
     * Getter de la tabla pedidos por cliente.
     *
     * @return JTable tblPedidosClientes donde se muestran los pedidos
     * realizados por un cliente.
     */
    public JTable getTblPedidosClientes() {
        return tblPedidosClientes;
    }

    /**
     * Getter del combobox de clientes.
     *
     * @return JComboBox cmbClientes1 donde se pueden seleccionar clientes.
     */
    public JComboBox getCmbClientes1() {
        return cmbClientes1;
    }

    /**
     * Getter del campo de texto total de pedidos
     *
     * @return JTextField txtTotalPedidos donde se suma el total de pedidos
     * realizados por un cliente seleccionado
     */
    public JTextField getTxtTotalPedidos() {
        return txtTotalPedidos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPedidos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedidosClientes = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        txtTotalPedidos = new javax.swing.JTextField();
        lblTotalPedidos = new javax.swing.JLabel();
        cmbClientes1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(204, 204, 255));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(1000, 650));
        setLayout(null);

        lblPedidos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPedidos.setText("Pedidos por cliente");
        add(lblPedidos);
        lblPedidos.setBounds(390, 10, 250, 50);

        tblPedidosClientes.setBackground(new java.awt.Color(204, 204, 255));
        tblPedidosClientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tblPedidosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre_Y_Apellidos", "IdVentas", "Fecha", "Hora", "Total"
            }
        ));
        tblPedidosClientes.setRowHeight(24);
        tblPedidosClientes.setRowMargin(2);
        jScrollPane1.setViewportView(tblPedidosClientes);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 140, 920, 420);

        lblNombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");
        add(lblNombre);
        lblNombre.setBounds(30, 80, 70, 30);

        btnConsultar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        add(btnConsultar);
        btnConsultar.setBounds(300, 80, 110, 30);

        txtTotalPedidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        add(txtTotalPedidos);
        txtTotalPedidos.setBounds(870, 590, 80, 30);

        lblTotalPedidos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTotalPedidos.setText("Total pedidos ");
        add(lblTotalPedidos);
        lblTotalPedidos.setBounds(770, 590, 110, 30);

        add(cmbClientes1);
        cmbClientes1.setBounds(90, 80, 200, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // Metodo de la clase accionesPedidosCliente que devuelve los pedidos por cliente en la tabla tblPedidosClientes   
        acciones.consultaPedidos();
        // Metodo de la clase accionesPedidosCliente que suma los valores de la columna total de tblPedidosClientes y lo muestra en el txtTotalPedidos
        acciones.sumaPedidosCliente();
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JComboBox<String> cmbClientes1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPedidos;
    private javax.swing.JLabel lblTotalPedidos;
    private javax.swing.JTable tblPedidosClientes;
    private javax.swing.JTextField txtTotalPedidos;
    // End of variables declaration//GEN-END:variables
}
