/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package punto.de.venta.principal;

import punto.de.venta.pantallas.PantallaCajaRegistradora;
import punto.de.venta.pantallas.PantallaPedidosCliente;
import punto.de.venta.pantallas.PantallaVentasDia;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import punto.de.venta.acciones.AccionesUsuarios;
import punto.de.venta.pantallas.PanelAjustesProductos;
import punto.de.venta.pantallas.PanelAjustesUsuarios;
import punto.de.venta.pantallas.PanelClientes;
import punto.de.venta.pantallas.PanelStock;
import punto.de.venta.pantallas.PanelListaUsuarios;

/**
 *
 * @author Jamal Hassini
 */
public class PuntoDeVentaFrame extends javax.swing.JFrame {

   JFrame CajaRegistradoraFrame = new JFrame();
    
    private AccionesUsuarios usuarios;
    
    public PuntoDeVentaFrame(AccionesUsuarios usuarios){
            
         this.usuarios=usuarios;
         
    }
    
    /**
     * Creates new form CajaRegistradoraFrame
     */
    public PuntoDeVentaFrame() {

        initComponents();

        PantallaCajaRegistradora verCaja = new PantallaCajaRegistradora(this);
        pnlContenedor.add(verCaja, java.awt.BorderLayout.CENTER);
        
        this.setSize(1000, 700);
    }

    public JMenu getMnuProductos() {
        return mnuProductos;
    }

    public JMenu getMnuUsuarios() {
        return mnuUsuarios;
    }

    public JMenuItem getMntmConfBotones() {
        return mntmStock;
    }  
     public JMenuItem getMnuCaja(){
         return mnuCaja;
     }
     public JMenuItem getMnuVentas(){
         return mnuVentas;
     }
     public JMenuItem getMnuPedidos(){
         return mnuPedidos;
     }
     public JMenuItem getMnuClientes(){
         return mnuClientes;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pnlContenedor = new javax.swing.JPanel();
        mnuBarra = new javax.swing.JMenuBar();
        mnuOpciones = new javax.swing.JMenu();
        mnuCaja = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenuItem();
        mnuPedidos = new javax.swing.JMenuItem();
        mnuClientes = new javax.swing.JMenu();
        mntmEMCliente = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenu();
        mnuCategorias = new javax.swing.JMenuItem();
        mntmStock = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnutmAjustesUsuarios = new javax.swing.JMenuItem();
        mnutmLista = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        setPreferredSize(new java.awt.Dimension(810, 600));
        setResizable(false);
        setSize(getPreferredSize());

        pnlContenedor.setMinimumSize(new java.awt.Dimension(1000, 650));
        pnlContenedor.setPreferredSize(new java.awt.Dimension(1000, 650));
        pnlContenedor.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContenedor, java.awt.BorderLayout.CENTER);

        mnuOpciones.setText("Opciones");

        mnuCaja.setText("Nuevo pedido");
        mnuCaja.setPreferredSize(new java.awt.Dimension(145, 22));
        mnuCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCajaActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuCaja);

        mnuVentas.setText("Pedidos por cliente");
        mnuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuVentas);

        mnuPedidos.setText("Ventas del día");
        mnuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPedidosActionPerformed(evt);
            }
        });
        mnuOpciones.add(mnuPedidos);

        mnuBarra.add(mnuOpciones);

        mnuClientes.setText("Clientes");

        mntmEMCliente.setText("Ajustes Clientes");
        mntmEMCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntmEMClienteActionPerformed(evt);
            }
        });
        mnuClientes.add(mntmEMCliente);

        mnuBarra.add(mnuClientes);

        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });

        mnuCategorias.setText("Ajustes productos");
        mnuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriasActionPerformed(evt);
            }
        });
        mnuProductos.add(mnuCategorias);

        mntmStock.setText("Estado Stock");
        mntmStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntmStockActionPerformed(evt);
            }
        });
        mnuProductos.add(mntmStock);

        mnuBarra.add(mnuProductos);

        mnuUsuarios.setText("Usuarios");

        mnutmAjustesUsuarios.setText("Ajustes Usuarios");
        mnutmAjustesUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnutmAjustesUsuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnutmAjustesUsuarios);

        mnutmLista.setText("Listar usuarios");
        mnutmLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnutmListaActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnutmLista);

        mnuBarra.add(mnuUsuarios);

        setJMenuBar(mnuBarra);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCajaActionPerformed
        // TODO add your handling code here:
        pnlContenedor.removeAll();
        String operari= PantallaCajaRegistradora.getLblOperario().getText();
        PantallaCajaRegistradora verCaja = new PantallaCajaRegistradora(this);
        PantallaCajaRegistradora.getLblOperario().setText(operari);
        pnlContenedor.add(verCaja, java.awt.BorderLayout.CENTER);
        
        pack();
        this.setSize(1000, 700);
        
        
    }//GEN-LAST:event_mnuCajaActionPerformed

    private void mnuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasActionPerformed
        // TODO add your handling code here:
        pnlContenedor.removeAll();
        PantallaPedidosCliente verPedidos = new PantallaPedidosCliente(this);
        pnlContenedor.add(verPedidos, java.awt.BorderLayout.CENTER);
        pack();
        this.setSize(1000, 700);
    }//GEN-LAST:event_mnuVentasActionPerformed

    private void mnuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPedidosActionPerformed
        // TODO add your handling code here:
        pnlContenedor.removeAll();
        PantallaVentasDia verVentas = new PantallaVentasDia(this);
        pnlContenedor.add(verVentas, java.awt.BorderLayout.CENTER);
        pack();
        this.setSize(1000, 700);
    }//GEN-LAST:event_mnuPedidosActionPerformed

    private void mntmEMClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmEMClienteActionPerformed
        // TODO add your handling code here:
        pnlContenedor.removeAll();
        PanelClientes bajaClientes = new PanelClientes(this);
        pnlContenedor.add(bajaClientes, java.awt.BorderLayout.CENTER);
        pack();
        this.setSize(1000, 700);
    }//GEN-LAST:event_mntmEMClienteActionPerformed

    private void mnuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriasActionPerformed
        // TODO add your handling code here:
        pnlContenedor.removeAll();
        PanelAjustesProductos categorias = new PanelAjustesProductos(this);
        pnlContenedor.add(categorias, java.awt.BorderLayout.CENTER);
        pack();
        this.setSize(1000, 700);
    }//GEN-LAST:event_mnuCategoriasActionPerformed

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void mntmStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmStockActionPerformed
        // TODO add your handling code here:
        //pnlContenedor.removeAll();
        PanelStock stock = new PanelStock();
        stock.setLocationRelativeTo(null);
        //pnlContenedor.add(botones, java.awt.BorderLayout.CENTER);
        stock.setVisible(true);
        //pack();
        //this.setSize(1000, 700);
    }//GEN-LAST:event_mntmStockActionPerformed

    private void mnutmAjustesUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnutmAjustesUsuariosActionPerformed
        // TODO add your handling code here:
        PanelAjustesUsuarios pnlnp= new PanelAjustesUsuarios();
        pnlnp.setLocationRelativeTo(null);
        pnlnp.setVisible(true);
    }//GEN-LAST:event_mnutmAjustesUsuariosActionPerformed

    private void mnutmListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnutmListaActionPerformed
        // TODO add your handling code here:
        PanelListaUsuarios panelU= new PanelListaUsuarios();
        panelU.setLocationRelativeTo(null);
        panelU.setVisible(true);
    }//GEN-LAST:event_mnutmListaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem mntmEMCliente;
    private javax.swing.JMenuItem mntmStock;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenuItem mnuCaja;
    private javax.swing.JMenuItem mnuCategorias;
    private javax.swing.JMenu mnuClientes;
    private javax.swing.JMenu mnuOpciones;
    private javax.swing.JMenuItem mnuPedidos;
    private javax.swing.JMenu mnuProductos;
    private javax.swing.JMenu mnuUsuarios;
    private javax.swing.JMenuItem mnuVentas;
    private javax.swing.JMenuItem mnutmAjustesUsuarios;
    private javax.swing.JMenuItem mnutmLista;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
